env = Environment()

src_files = Glob('*.cpp')

# -g for debugging
env.Append(CCFLAGS = ['-g'])
env['CXXFLAGS']=['-std=c++11']

main = env.Program(
    target = 'main',
    source = src_files,
    )

command = main[0].abspath
var = env.Alias('main', main, command)
env.AlwaysBuild(var)
