env = Environment()

env['GTEST_DIR'] = '#../external/gtest-1.7.0'	
env['GTEST_INCL_DIR'] = '${GTEST_DIR}/include'		
env['GTEST_LIB_DIR'] = '${GTEST_DIR}/make'

env.Append(CPPPATH = [
	'.',
	'${GTEST_INCL_DIR}',
	])

# -g for debugging
env.Append(CCFLAGS = ['-g',
	'-std=c++11'
	])

# I do not why, but including the '..' in next line in LIBS directory, doesn't work.
gtest = env.File('${GTEST_LIB_DIR}/gtest_main.a')
# libs to link against 
env.Append(LIBS = [
	gtest,
	'pthread'
	])
	
src_files = Glob('*.cpp')
 
main = env.Program(
    target = 'main',
    source = src_files,
    )


command = main[0].abspath
var = env.Alias('tests', main, command)
env.AlwaysBuild(var)
