env = Environment()

env['GTEST_DIR'] = '#../external/gtest-1.7.0'		
env['GTEST_INCL_DIR'] = '${GTEST_DIR}/include'		
env['GTEST_LIB_DIR'] = '${GTEST_DIR}/make'
env['IOUTILS_DIR'] = '#../io-utils'
env['RAPIDXML_DIR'] = '#../external/rapidxml-1.13'

env.Append(CPPPATH = [
	'.',
	'${GTEST_INCL_DIR}',
	'${IOUTILS_DIR}',
	'${RAPIDXML_DIR}',
	])

# -g for debugging
env.Append(CCFLAGS = ['-g',
	'-std=c++11'
	])

gtest = env.File('${GTEST_LIB_DIR}/gtest_main.a')
# libs to link against 
env.Append(LIBS = [
	gtest,
	'pthread'
	])
	
env.Append(LIBPATH = [
	'.'
	])	

src_files = Glob('*.cpp')
external_files = [
	'${IOUTILS_DIR}/IOUtils.cpp'
	]
 
env.Program(
    target = 'main',
    source = src_files + external_files,
    )
